### ISSUE TITLE
Meson build system

### ISSUE THREAD

**Issue by fushinari** [fushinari/Wordbook#10]
Currently, Wordbook uses setuptools for packaging. Meson is a better solution for desktop applications, especially one that focuses on the GTK side of things.

**Comment by joshbowyer** [comment]
This would be a great dictionary app for mobile Linux phones (Pinephone/Librem5); using meson for packaging would allow it to be easily included (and even a flatpak)

**Comment by fushinari** [comment]
I could flatpak it as is. I just don't think that it should be used in its current state. There're too many things wrong with it. Like #12 . Also, the current state of the dictionary part itself isn't great either. I hope to fix that with #13 so that I can just work on the other bits slowly but it's not going as smoothly as I'd have liked it to. The pronunciation part will probably be made opt-in with a warning.

I don't think I'll be switching to Meson any time soon. I just keep this issue open because it's something I want to do at some point but not quite yet. As clunky as setuptools may seem, it's definitely easier to work with than Meson.
