### ISSUE TITLE
Proper icon following the GNOME HIG

### ISSUE THREAD

**Issue by fushinari** [fushinari/Wordbook#11]
The only icon until 791964665e5c6973ed9ab728e7a38bec955aeff6 was the system `accessories-dictionary` icon. Now, there's a rough icon in `data/icons` that follows the GNOME HIG and using the Adwaita template.

I have no skills when it comes to designing. So, hopefully someone can help me out with this at some point.

**Comment by GustavoPeredo** [comment]
I'm no designer as well, but I did do some redesigns that you might consider taking a look at:
![Wordbook](https://user-images.githubusercontent.com/30641461/110370982-22c1b000-802b-11eb-83b1-8c5192f96791.png)
![Wordbook2](https://user-images.githubusercontent.com/30641461/110370989-23f2dd00-802b-11eb-8d0d-7c098a386f9f.png)
What do you think?

**Comment by fushinari** [comment]
Wow, these are amazing! I particularly like the first one! I'd gladly accept a PR with one of these. :) Thank you for your work on this!

**Comment by fushinari** [comment]
Is there also a symbolic variant?

**Comment by GustavoPeredo** [comment]
Not yet, but I'll make one and create a PR ;)

**Comment by GustavoPeredo** [comment]
Before that, I'd like to know which symbolic do you prefer? (I suggest opening them on a new browser tab and zooming in them)

![com github fushinari Wordbook-symbolic2](https://user-images.githubusercontent.com/30641461/110544103-f3ce3b80-8109-11eb-95c9-a159122027c1.png)

![com github fushinari Wordbook-symbolic](https://user-images.githubusercontent.com/30641461/110544011-d8633080-8109-11eb-8e92-331762af280a.png)

Although I think "W" doesn't convey words as much, "Words" feels like too long of a text for GNOME's top bar.

**Comment by fushinari** [comment]
> Although I think "W" doesn't convey words as much, "Words" feels like too long of a text for GNOME's top bar.

I agree. The first variant is not very viewable. The second variant's "W" with the underline still looks great and works though. So no worries :)

**Comment by GustavoPeredo** [comment]
Awesome! I'm creating the PR

**Comment by fushinari** [comment]
Fixed by #19
