### ISSUE TITLE
Wordbook won't start

### ISSUE THREAD

**Issue by fastrizwaan** [fushinari/Wordbook#14]
* Wordbook version: latest git hub on 23 dec 2020
* Python version: 3
* Operating System: fedora 33 x86_64

### Description

```
 git clone https://github.com/fushinari/wordbook.git
 cd wordbook/
 sudo python setup.py install
  wordbook
  pip install wn
  wordbook
  sudo pip install WordNet
  wordbook
  pip install python-wn
  pip install python-wn
  pip install wn
  wordbook
```
fails to launch
```
[rizvan@localhost wordbook]$ wordbook
Traceback (most recent call last):
  File "/usr/local/bin/wordbook", line 33, in <module>
    sys.exit(load_entry_point('wordbook==0.1.0', 'gui_scripts', 'wordbook')())
  File "/usr/local/bin/wordbook", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/site-packages/wordbook-0.1.0-py3.9.egg/wordbook/gtk/__init__.py", line 13, in <module>
    from .main import main
  File "/usr/local/lib/python3.9/site-packages/wordbook-0.1.0-py3.9.egg/wordbook/gtk/main.py", line 15, in <module>
    from wordbook import base, utils  # noqa
  File "/usr/local/lib/python3.9/site-packages/wordbook-0.1.0-py3.9.egg/wordbook/base.py", line 22, in <module>
    from wn import WordNet
ImportError: cannot import name 'WordNet' from 'wn' (/usr/local/lib/python3.9/site-packages/wn/__init__.py)

```

**Comment by fushinari** [comment]
Glad to see someone trying it, but right now, `master` is broken. The branch `new-wn`(see #13 ) has a WIP but working (I think?) state of it. I was planning to work on it in these few days but sadly, I've fallen sick. But hopefully, I should be able to get it properly working sooner rather than later.

**Comment by fastrizwaan** [comment]
If it works, and you make a release, we can put it in Flathub, or at least I can make a flatpak. Good software should be available to all.
Please add history support using Back and Forward buttons, that way the headerbar would  also look good.

I'll try the new-wn branch. Thank you

**Comment by fushinari** [comment]
I won't be adding back and forward buttons. I do plan to use HdyFlap to present history among other things and then add shortcuts for back and forward. I don't want to crowd up the HeaderBar.

Stable release is a really long time away and a lot of work is needed before that. Right now would've been the perfect time to work on it if I wasn't sick but my brain really isn't working right now lol.

**Comment by fastrizwaan** [comment]
Ok I downloaded wordbook-wn brach, ran, it downloaded wordnet, but after that 
Random Word gives error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/wordbook-0.1.0-py3.9.egg/wordbook/gtk/window.py", line 126, in on_random_word
    random_word = random.choice(self._wn_future.result()["list"])
  File "/usr/lib64/python3.9/random.py", line 346, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range
```

Search for a word is also not giving results. Looks like wordnet db is not read?
![Screenshot from 2020-12-25 05-26-06](https://user-images.githubusercontent.com/1161682/103111331-ea3c4800-4671-11eb-8c43-579de9a84286.png)

And regarding Crowding the headerbar, the [<x] button is redundant.
The headerbar feels uneven with Lineedit on the left most, perhaps wordbook icon before lineedit will make it look balanced. We are used to see Line edit in Center.

What happened to you Mufeed Bhai? Btw, take soaked Almonds, it will really help your creativity, forucs which is required for programming.

**Comment by fushinari** [comment]
The UI's general appearance will not be changing for now. I want to keep it true to my ideals. Of course, I'll change it if I feel like it, but right now, I don't. The clear button isn't redundant but I might move it's functionality elsewhere, like I did with the voice pronunciation button before. There are a lot of other things that I'm working on though.

The `new-wn` branch will soon be updated. I have switched to meson, removed the Qt5 UI, added support for the new callback progress update mechanism in wn, etc among other changes. I will also make the pronunciations an opt-in feature soon because it isn't really reliable for now.

Also, may I ask what icon theme you're using? That's not how the application is supposed to look with any decent icon theme or the default Adwaita.

**Comment by fastrizwaan** [comment]
Yes, the search icon is different as It's my own Icon theme. https://github.com/fastrizwaan/Martian-Wheel

**Comment by fushinari** [comment]
Ah, glad to know it's not breakage on my end. Thanks for reporting this. I guess I was a bit too unconcerned about it.

**Comment by fastrizwaan** [comment]
glad to see you back with WordBook. In the meanwhile I also got Artha to work. But now I would love to use WordBook instead of Artha.
