### ISSUE TITLE
Flatpak issues

### ISSUE THREAD

**Issue by fushinari** [fushinari/Wordbook#17]
I'm not very familiar with flatpak. So, any help on this would be much appreciated.

- [x] ~`espeak-ng` is not included in the Flatpak. So, pronunciations and audio don't work yet. I get weird errors when building espeak-ng.~ Fixed in e30f0143fd68b72dde024e1bf0c754e60d5cd45d.
- [ ] I don't know how to declare build dependencies separately from runtime dependencies. For example, `python3-flit-core` is a build dependency for `python3-wn`, so the flatpak itself does not need to include flit-core but I found no other way to make it work.
- [x] ~Most probably many other issues I haven't noticed yet...~

**Comment by fastrizwaan** [comment]
HI,

espeak-ng does not sound natural. Instead we can use google voice using . https://pypi.org/project/gTTS/

Have a look at for python3 based 
https://github.com/fastrizwaan/deluge_flatpak/blob/main/big-source-based-yaml/com.github.deluge.yaml

**Comment by fastrizwaan** [comment]
here's espeak-ng json 
https://github.com/flathub/org.sugarlabs.Words/blob/master/org.sugarlabs.Words.json

**Comment by fastrizwaan** [comment]
Working google text to speech python3 program

Requirements:
```
pip install gtts
pip insall playsound
```
speak.py
```
#!/usr/bin/python3
import os
import sys, getopt
import time
import playsound
#import speech_recognition as sr
from gtts import gTTS

def speak(text):
    tts = gTTS(text=text, lang="en")
    filename="voice.mp3"
    tts.save(filename)
    playsound.playsound(filename)
print(sys.argv[1:])
speak(str(sys.argv[1:]))

```
test
```
./speak.py "Hello Hello Wordbook Maker"
```

**Comment by fushinari** [comment]
Hi,
Sorry for not replying earlier.

I won't be using gTTS for many reasons. I want Wordbook to be fully offline after the initial database download. We use gTTS for https://github.com/gi-lom/dialect, so I'm very familiar with it by now. But I'd rather not use it in this case. I don't really want natural-sounding TTS and want to provide IPA phonemes. espeak-ng matches my preferences and goals.

On another note, I had already fixed the espeak-ng issue. For some reason, it does not build with GCC, so I had to force it to use Clang instead. I was planning to push those changes along with a few others (python-wn downgrade because 0.4.0 is broken for me) but I haven't really gotten around to it. So, expect some updates soon.

**Comment by fushinari** [comment]
The espeak dependency has been fixed in e30f0143fd68b72dde024e1bf0c754e60d5cd45d.

**Comment by fushinari** [comment]
@fastrizwaan Btw, I removed the clear button like you said. I'd entirely forgotten that you can clear it by simply searching an empty string.

**Comment by fastrizwaan** [comment]
Just waiting for the flatpak :-)

**Comment by fushinari** [comment]
@fastrizwaan The flatpak is already ready and you can try out its current fully-working state by downloading and installing the latest CI artifact. For example, https://github.com/fushinari/Wordbook/suites/1862467542/artifacts/36214621 . There are a few more issues to work through before publishing on Flathub if that's what you mean though.

**Comment by fastrizwaan** [comment]
Good job! I think Wordbook needs a few more important features, like 
Artha: grammatical search, like plurals (car-> cars) and verb forms (add-> adds, added, adding)
DropDown listing: on typing live-search only show matches, whereas artha shows all available words in the dropdown list
https://github.com/fastrizwaan/Artha_flatpak/raw/main/Artha.flatpak

Normal word "Add"
![add](https://user-images.githubusercontent.com/1161682/105258507-ebe52700-5baf-11eb-902a-545222df25d5.png)
Artha handles "verb forms" (added, adding, adds)
![added](https://user-images.githubusercontent.com/1161682/105258527-f69fbc00-5baf-11eb-8760-09b45326dd76.png)

**Comment by fushinari** [comment]
Thanks for testing!

About the grammatical search, I think I get you and if it's easy enough, I'll be implementing it soon. :)

Regarding the drop-down listing, I don't understand what you mean.

I had disabled the auto-completion for live search and if you think it's useful to have, I'll re-enable it.

If what you mean is that all words should be part of the list and then matching should be done later, I'm not really sure how I'd go about doing that without a performance impact. :(

**Comment by fastrizwaan** [comment]
You're welcome. It would be nice to see all words with starting with substring, when we are typing:
![artha-dropdown](https://user-images.githubusercontent.com/1161682/105283610-d6cfbe80-5bd6-11eb-9e77-b34920cab039.png)

Kdictionary, also does similarly https://github.com/keshavbhatt/Kdictionary
![Uploading Screenshot from 2021-01-21 10-54-28.png…]()

**Comment by fushinari** [comment]
Auto-completion is there. It's just disabled when using live search.
