### ISSUE TITLE
support for --look-up argument

### ISSUE THREAD

**Issue by aredcomet** [fushinari/Wordbook#21]
* Wordbook version: 0.20
* Python version: flatpak
* Operating System: pop os (flatpak)

### Description

This app is  handy and better (in terms of word meanings as it uses wordnet over a century old free dictionary like gnome dictionary & offline). Thanks for making for making this app, It will be all more useful if support for lookup word is added as named argument.

Gnome Dictionary doesn't support search from clipboard but offers a way using mentioned  argument, when combined with tools like `xsel` and custom keyboard shortcut, its as good as copying from clipboard (mentioned in gnome 40 issue).

For reference, I'm using below command, configured to run with ctrl+alt+w opens up app with the word selected (buffer)

```bash
flatpak run org.gnome.Dictionary --look-up=$(xsel)
```

**Comment by fushinari** [comment]
Hi,

Glad to know you like the app!

Thanks for the nice suggestion! I've added it in ea91d42ee7fe8b08082fd06d7d27c064f2f00ad9 . It will be present in 0.3.0, which is very soon! If you'd like to test it asap, you can try the [CI build](https://github.com/fushinari/Wordbook/suites/2543625447/artifacts/55244429).

**Comment by aredcomet** [comment]
Thanks for fast revert, sure I will check it :+1:

**Comment by fushinari** [comment]
0.3.0 might be a bit delayed because I'm working on #22 but since the feature is already in main, I'm closing this. Please re-open if you see any issues with the implementation :)
