### ISSUE TITLE
Lack of free space in header

### ISSUE THREAD

**Issue by dartvader316** [fushinari/Wordbook#26]
* Wordbook version: 0.3.1 (flatpak)
* Operating System: debian 11
* Desktop Environment: Gnome 3.38.5

### Description

The Wordbooks's window header is always fully filled with buttons and search bar, even maximized. Such header is used to drag windows (at least in Gnome 3.XX). So to drag Wordbook window i have to use a little space between elements in header, which is not so easy. Can you fix this with adding some free space into header? My suggestions are to disable auto width of search bar or to add some padding. You can also make use of free header space by adding the centered name of your app there.

![Screenshot from 2021-09-20 21-34-36](https://user-images.githubusercontent.com/20815458/134056025-08a776f0-0e02-4886-9087-86bfa928db84.png)

**Comment by fushinari** [comment]
You can drag by any of the buttons too. That said, I'm working on some changes that will hopefully address this a bit better.
