### ISSUE TITLE
Webster's Dictionary?

### ISSUE THREAD

**Issue by canadaduane** [fushinari/Wordbook#29]
Just a suggestion--would it be possible to also search Webster's dictionary?

For example, this data source:
https://github.com/ponychicken/WebsterParser

I was inspired by [a blog post](https://jsomers.net/blog/dictionary) about how Webster's dictionary inspires authors to find alternative phrasing and ideas while using a dictionary.

**Comment by fushinari** [comment]
Sorry, I have no plan to add support for any dictionary other than the Open English WordNet.
